# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Pong/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Pong)

$(call add-radio-file-sha1-checked,radio/abl.img,6caf8234a47101e2e3463753a8a41fc8c4d47b62)
$(call add-radio-file-sha1-checked,radio/aop.img,bc9e89a682f3424bae15cdcaf1fafd0e31f8a517)
$(call add-radio-file-sha1-checked,radio/aop_config.img,5b426b499bd430e15a5875bc7df2661d3bc1295c)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,69cb190d0507603b698ad457497fec359176c344)
$(call add-radio-file-sha1-checked,radio/cpucp.img,1ff7c446e9ca9958fdfec11b6ea0a7a120693b23)
$(call add-radio-file-sha1-checked,radio/devcfg.img,1196a10692cd3bc475f9810e290ccf296ad17210)
$(call add-radio-file-sha1-checked,radio/dsp.img,6e5cb80bf33ed5a585756db2241240de2cd371a8)
$(call add-radio-file-sha1-checked,radio/featenabler.img,9fa58aee1065015c167cb50c6fe9778f9d87a587)
$(call add-radio-file-sha1-checked,radio/hyp.img,9f629d078939a132a525858f24a2b380ae93721e)
$(call add-radio-file-sha1-checked,radio/imagefv.img,1a4dc32b725816f31b4f597b23ed34c8fdd624e5)
$(call add-radio-file-sha1-checked,radio/keymaster.img,aaec06e956c4387e504797e54f0369f2c26c2aad)
$(call add-radio-file-sha1-checked,radio/modem.img,6f9a8901925220c885b969339d451d07c9f280d2)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,3a58f6b1d72e064c5b69de59f9102820dc120429)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,91dc0a65c3a872e533b8716d01bd1f5a2e652b10)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0096cae364594c3698830142b38e68ec8e9c5e05)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,4b58b191da6e295907a183cabaa20d1d077dcd47)
$(call add-radio-file-sha1-checked,radio/tz.img,e68ae6bdd0365dedbbf6dbcbc7801e751367904f)
$(call add-radio-file-sha1-checked,radio/uefi.img,c928b9ed816d5e6aeb50164abf35adf3f00d56d1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9a7d71140c51a4f5fc080094c7f5b2a107c82d4b)
$(call add-radio-file-sha1-checked,radio/xbl.img,051bcfe931583be0741fbfa654e3f1d629ac70fb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,88ad7034e11bb8e7a3b3323be50c7e3250878b9d)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,f929da3a438e07917851f9e255b61e4733da66a7)

endif
