# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Pong/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Pong)

$(call add-radio-file-sha1-checked,radio/abl.img,6f17cdcfdb8636bfeb85a04b0def75ebd7b972ce)
$(call add-radio-file-sha1-checked,radio/aop.img,1f769f7b3e1250ce5a8963be227c000951709ad3)
$(call add-radio-file-sha1-checked,radio/aop_config.img,d29de31c570aa17884993d1cc4999f98acbeb77f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,aec601b19479379899e3e227dec15d1edc5a9bb6)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f9042783e79de4a649d63c6b94d232613380d94a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f4c13165365a9360440fe0481d9b2e969c1942ea)
$(call add-radio-file-sha1-checked,radio/dsp.img,6e5cb80bf33ed5a585756db2241240de2cd371a8)
$(call add-radio-file-sha1-checked,radio/featenabler.img,4c5ee043905dec9f25d7347243409aeb6b5fd8e9)
$(call add-radio-file-sha1-checked,radio/hyp.img,5173b0d33a87077a337153a2680f012eb28b85d3)
$(call add-radio-file-sha1-checked,radio/imagefv.img,39c98380c579b712486de1355ee399ef91deda53)
$(call add-radio-file-sha1-checked,radio/keymaster.img,246909bdba03aa3b6381113366418ebd24939724)
$(call add-radio-file-sha1-checked,radio/modem.img,bd9bf6993d51627b05230a7f8555697484af4042)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,c9757cdafc8397dd387463800a8597eac9c465d8)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,91dc0a65c3a872e533b8716d01bd1f5a2e652b10)
$(call add-radio-file-sha1-checked,radio/qupfw.img,428d9d14e332694715dc3cb6eef6d68db9d3b618)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,b9dd81e1c0a4fd4605189c11f978cb710068226f)
$(call add-radio-file-sha1-checked,radio/tz.img,4b0835f1952635e31661f70e336ca0ba86410048)
$(call add-radio-file-sha1-checked,radio/uefi.img,0488c6a14b17b9f87d99867143ee3d6559d01b22)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a5876150958e3f94afd4e8f9f14945927a2da607)
$(call add-radio-file-sha1-checked,radio/xbl.img,c409d9d96cd3c3d22d73180e544b50d47fb0fcf4)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2ca1b3d71101f2b7dcca017cd95b456769ddaa04)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,21cd268e63cecbaa365d21c24d45ea74d2c15861)

endif
